version: 2
jobs:
  test:
    docker:
      - image: docker:18.03
    working_directory: /data
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            docker build -t kolemp/twig-renderer:latest .
            docker run --rm -e "TEST_MODE=1" kolemp/twig-renderer:latest
  build:
    docker:
      - image: docker:18.03
    working_directory: /data
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run:
          command: |
            docker build -t kolemp/twig-renderer:latest .
            docker run --rm -e "TEST_MODE=1" kolemp/twig-renderer:latest
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push kolemp/twig-renderer:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - build:
          filters:
            branches:
              only: master

